sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Id4gWagvpW6TVcaZ9SzW30AAaJmWyjfaadlIoGN6yWNRA5JKuxU7NbPwmAAWlLLNhKdLo5CMJiEPDj7r+jyE9AIBRoCiEg98fyA11yNIuzoSaKcENgJZbx4mjSuQ4Xnj9atGcgXPUJvkyarNN7kSdmmId+Po0fU5SIKtSKnEAOGT8EdtVbEXKhd6PAkk9N3+deIH0mhRBnt7r4QYPvJckoQqJy162LGHOolVP0+SczfObDlyrSvwynupVSa37uD2Br9k3XK1NpwqTP/aKAM9cLnMXnxJpIc7qEEzkLpO3Ww23yN5ZQYBRlCEDUTxtsBYpeePHI625CesRNP+xeJhdSCVJyYdADD71ondtoSOuXPzuvi1M91Z04MG041YBmCaOum/4lf7aOABcY+FujeVMR2034LhSJDt/c98dUJC2YsBsCT4SfYZLjyZhodqbdcLzZ/fGqHjFZxtdM+pzdnrJCPkb40n4PgNiOVT1Jmu6L1WfptHOC0YCBEKR9xLMecGb9PpjE0RsBRKMs+IkW9hCyBdgzCvbtKPW6JvIBvYRP5d156xSGp9u27RCnso9Po/KnbenB0eeGorxFc+5aPZPWT0Doi4iqCbcodoy48Ux5xweA9KMZ0DqIvcsPI1qoz183DDQEW+6YifLVt5Ie+jrB7FyJGEpD8SozVa9FtrMGg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Cleveland-Era--A-Chronicle-of-the-New-Order-in-Politics_3041
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy